apiVersion: v1
kind: Namespace
metadata:
  name: reporting
---
apiVersion: v1
kind: Namespace
metadata:
  name: mediakube
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: network-dashboard
  namespace: reporting
spec:
  entryPoints:
    - web
  routes:
    - match: (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService