{{ if ne .Values.image.domainPath "" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-devicemanager
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: (PathPrefix("/{{ .Values.image.domainPath }}"))
      kind: Rule
      services:
        - name: {{ include ".helm.fullname" . }}
          kind: Service
          port: {{ .Values.image.containerPort }}
      middlewares:
      - name: "{{ include ".helm.fullname" . }}-strip"
{{ end }}